URL_TERMINAL_REGISTRATION = '/api/v2/terminal/terminal-registrations/'
URL_USER_PROFILE = '/api/v1/users/profile/'
URL_USER_DATABASE_PERMISSION_VALIDATE = '/api/v1/perms/database-app-permissions/user/validate/'
URL_DATABASE_DETAIL = '/api/v1/applications/database-apps/{database_id}/'
URL_SYSTEM_USER_DETAIL = '/api/v1/assets/system-users/{system_user_id}/'
URL_SYSTEM_USER_AUTH_INFO = '/api/v1/assets/system-users/{system_user_id}/auth-info/'
URL_SESSION = '/api/v1/terminal/sessions/'
URL_COMMAND = '/api/v1/terminal/commands/'
